export const worksItems = [
    {
        id: '1',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
    {
        id: '2',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
    {
        id: '3',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
    {
        id: '4',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
    {
        id: '5',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
    {
        id: '6',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
    {
        id: '7',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
    {
        id: '8',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
    {
        id: '9',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
    {
        id: '10',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
    {
        id: '11',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
    {
        id: '12',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
    {
        id: '13',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
    {
        id: '14',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
    {
        id: '15',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
    {
        id: '16',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
    {
        id: '17',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
    {
        id: '18',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
    {
        id: '19',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },{
        id: '20',
        date: new Date().toLocaleString(),
        address: 'ул.Пушкина, д. 8',
        userName: 'Артемий Татьянович',
        workType: 'шараж-монтаж',
    },
]